{% set name = "spectral-cube" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 71c62c336a8f9b216cfee5fae2ab86a032df323d41f684ec44cb796d44d6f19f

  # The following patch is needed because pip doesn't allow flags to be passed to the egg_info
  # step, and we need to pass --offline and --no-git. This can be updated once the following
  # issue is fixed: https://github.com/pypa/pip/issues/4383
  patches:
    - setup.cfg.patch

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python
    - setuptools >=30.3
    - setuptools_scm
  run:
    - python
    - astropy
    - numpy >=1.8.0
    - radio-beam >=0.2
    - six
    - dask
    - joblib

test:
  imports:
    - spectral_cube

about:
  home: http://spectral-cube.readthedocs.io
  license: BSD 3-clause
  license_family: BSD
  license_file: LICENSE.rst
  summary: A package for interaction with spectral cubes
  description: |
    The spectral-cube package provides an easy way to read, manipulate,
    analyze, and write data cubes with two positional dimensions and one
    spectral dimension, optionally with Stokes parameters. It provides  a
    uniform interface to spectral cubes, robust to the wide range of
    conventions of axis order, spatial projections, and spectral units that
    exist in the wild. It also allows easy extraction of cube sub-regions
    using physical coordinates and the ability to easily create, combine, and
    apply masks to datasets. It is designed to work with datasets too large to
    load into memory.
  doc_url: http://spectral-cube.readthedocs.io
  dev_url: https://github.com/radio-astro-tools/spectral-cube

extra:
  recipe-maintainers:
    - mwcraig
    - bsipocz
    - keflavich
    - astrofrog-conda-forge
