{% set name = "spectral-cube" %}
{% set version = "0.4.1" %}
{% set hash_type = "sha256" %}
{% set hash_value = "bf0dbe530bfb956e4670f0643f9aa50c31822cd723c43435cbd04f0649d688ab" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  fn: '{{ name }}-{{ version }}.tar.gz'
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  '{{ hash_type }}': '{{ hash_value }}'

build:
  number: 0
  script: python setup.py install --offline --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools
    - astropy
    - numpy >=1.8.0
  run:
    - python
    - astropy
    - numpy >=1.8.0

test:
  imports:
    - spectral_cube

about:
  home: http://spectral-cube.readthedocs.io
  license: BSD 3-clause
  license_family: BSD
  license_file: LICENSE.rst
  summary: A package for interaction with spectral cubes
  description: |
    The spectral-cube package provides an easy way to read, manipulate,
    analyze, and write data cubes with two positional dimensions and one
    spectral dimension, optionally with Stokes parameters. It provides  a
    uniform interface to spectral cubes, robust to the wide range of
    conventions of axis order, spatial projections, and spectral units that
    exist in the wild. It also allows easy extraction of cube sub-regions
    using physical coordinates and the ability to easily create, combine, and
    apply masks to datasets. It is designed to work with datasets too large to
    load into memory.
  doc_url: http://spectral-cube.readthedocs.io
  dev_url: https://github.com/radio-astro-tools/spectral-cube

extra:
  recipe-maintainers:
    - mwcraig
    - bsipocz
    - keflavich
